-- Seed additional Bible questions
INSERT INTO "Biblia" (
    "enunciado",
    "alternativaA",
    "alternativaB",
    "alternativaC",
    "alternativaD",
    "alternativaE",
    "respostaCorreta",
    "ranking",
    "updatedAt"
) VALUES
('Quem foi a primeira mulher criada por Deus?', 'Sara', 'Eva', 'Rebeca', 'Raquel', 'Miriã', 'B', 21, CURRENT_TIMESTAMP),
('Qual era o sinal da aliança de Deus com Noé após o dilúvio?', 'Uma estrela', 'Uma nuvem', 'O arco-íris', 'Uma pomba', 'Uma coluna de fogo', 'C', 22, CURRENT_TIMESTAMP),
('Qual era o nome original de Abraão?', 'Abrão', 'Jacó', 'Isaque', 'Israel', 'Ló', 'A', 23, CURRENT_TIMESTAMP),
('Qual era o nome da esposa de Abraão?', 'Rebeca', 'Sara', 'Raquel', 'Lia', 'Ester', 'B', 24, CURRENT_TIMESTAMP),
('Quem foi o filho prometido a Abraão e Sara?', 'Ismael', 'Esaú', 'Isaque', 'Jacó', 'José', 'C', 25, CURRENT_TIMESTAMP),
('Quem vendeu seu direito de primogenitura por um prato de lentilhas?', 'Jacó', 'Esaú', 'José', 'Judá', 'Rúben', 'B', 26, CURRENT_TIMESTAMP),
('Qual era o novo nome dado a Jacó?', 'Abraão', 'Israel', 'Samuel', 'Elias', 'Josué', 'B', 27, CURRENT_TIMESTAMP),
('Quantos filhos Jacó teve que deram origem às tribos de Israel?', '10', '11', '12', '13', '14', 'C', 28, CURRENT_TIMESTAMP),
('Qual filho de Jacó recebeu uma túnica colorida?', 'Judá', 'Levi', 'José', 'Benjamim', 'Simeão', 'C', 29, CURRENT_TIMESTAMP),
('Para qual terra José foi levado como escravo?', 'Babilônia', 'Assíria', 'Egito', 'Moabe', 'Filístia', 'C', 30, CURRENT_TIMESTAMP),
('Quem encontrou Moisés ainda bebê no rio?', 'A rainha de Sabá', 'A filha de Faraó', 'Miriã', 'Débora', 'A esposa de Faraó', 'B', 31, CURRENT_TIMESTAMP),
('De que material era o cesto onde Moisés foi colocado?', 'Madeira de cedro', 'Junco', 'Pedra', 'Barro', 'Palha de trigo', 'B', 32, CURRENT_TIMESTAMP),
('Qual praga transformou a água do Egito em sangue?', 'Primeira praga', 'Terceira praga', 'Quinta praga', 'Sétima praga', 'Décima praga', 'A', 33, CURRENT_TIMESTAMP),
('Qual foi a última praga enviada ao Egito antes da saída dos israelitas?', 'Gafanhotos', 'Trevas', 'Morte dos primogênitos', 'Saraiva', 'Rãs', 'C', 34, CURRENT_TIMESTAMP),
('Qual mar Deus abriu para o povo de Israel passar?', 'Mar Morto', 'Mar Vermelho', 'Mar da Galileia', 'Mar Mediterrâneo', 'Mar de Tiberíades', 'B', 35, CURRENT_TIMESTAMP),
('O que Deus enviou do céu para alimentar Israel no deserto?', 'Peixes', 'Pães', 'Maná', 'Uvas', 'Mel', 'C', 36, CURRENT_TIMESTAMP),
('Quem foi o irmão de Moisés?', 'Calebe', 'Arão', 'Josué', 'Gideão', 'Samuel', 'B', 37, CURRENT_TIMESTAMP),
('Quem foi a irmã de Moisés?', 'Rute', 'Débora', 'Miriã', 'Ana', 'Abigail', 'C', 38, CURRENT_TIMESTAMP),
('Quem acompanhou Josué como espia fiel da terra prometida?', 'Gideão', 'Calebe', 'Sansão', 'Samuel', 'Eli', 'B', 39, CURRENT_TIMESTAMP),
('Qual cidade teve suas muralhas derrubadas após Israel marchar ao redor dela?', 'Jericó', 'Betel', 'Hebrom', 'Samaria', 'Damasco', 'A', 40, CURRENT_TIMESTAMP),
('Quem escondeu os espias israelitas em Jericó?', 'Rute', 'Raabe', 'Débora', 'Ester', 'Jael', 'B', 41, CURRENT_TIMESTAMP),
('Qual juiz de Israel era conhecido por sua grande força?', 'Gideão', 'Sansão', 'Jefté', 'Eúde', 'Baraque', 'B', 42, CURRENT_TIMESTAMP),
('Qual mulher descobriu o segredo da força de Sansão?', 'Dalila', 'Débora', 'Jael', 'Rute', 'Bate-Seba', 'A', 43, CURRENT_TIMESTAMP),
('Quem liderou trezentos homens contra os midianitas?', 'Sansão', 'Gideão', 'Josué', 'Saul', 'Davi', 'B', 44, CURRENT_TIMESTAMP),
('Quem foi uma juíza e profetisa em Israel?', 'Rute', 'Débora', 'Ester', 'Ana', 'Miriã', 'B', 45, CURRENT_TIMESTAMP),
('Qual mulher moabita decidiu seguir Noemi e o Deus de Israel?', 'Orfa', 'Rute', 'Raquel', 'Lia', 'Tamar', 'B', 46, CURRENT_TIMESTAMP),
('Quem foi o marido de Rute?', 'Boaz', 'Elimeleque', 'Obede', 'Jessé', 'Samuel', 'A', 47, CURRENT_TIMESTAMP),
('Qual mulher orou por um filho e prometeu dedicá-lo a Deus?', 'Ana', 'Sara', 'Rebeca', 'Raquel', 'Ester', 'A', 48, CURRENT_TIMESTAMP),
('Quem foi o sacerdote que cuidou de Samuel no templo?', 'Eli', 'Arão', 'Zadoque', 'Abiatar', 'Melquisedeque', 'A', 49, CURRENT_TIMESTAMP),
('Quem foi o primeiro rei de Israel?', 'Davi', 'Salomão', 'Saul', 'Roboão', 'Jeroboão', 'C', 50, CURRENT_TIMESTAMP),
('Qual profeta ungiu Davi como rei?', 'Elias', 'Eliseu', 'Samuel', 'Natã', 'Isaías', 'C', 51, CURRENT_TIMESTAMP),
('Qual era a profissão de Davi antes de se tornar rei?', 'Carpinteiro', 'Pastor de ovelhas', 'Pescador', 'Sacerdote', 'Ferreiro', 'B', 52, CURRENT_TIMESTAMP),
('Qual instrumento Davi tocava para acalmar Saul?', 'Trombeta', 'Harpa', 'Flauta', 'Tambor', 'Címbalo', 'B', 53, CURRENT_TIMESTAMP),
('Quem foi o grande amigo de Davi, filho de Saul?', 'Absalão', 'Jônatas', 'Joabe', 'Natã', 'Adonias', 'B', 54, CURRENT_TIMESTAMP),
('Quem confrontou Davi após seu pecado com Bate-Seba?', 'Samuel', 'Natã', 'Elias', 'Gade', 'Abiatar', 'B', 55, CURRENT_TIMESTAMP),
('Qual filho de Davi pediu sabedoria a Deus?', 'Absalão', 'Adonias', 'Salomão', 'Amnom', 'Daniel', 'C', 56, CURRENT_TIMESTAMP),
('Quem construiu o primeiro templo em Jerusalém?', 'Davi', 'Salomão', 'Saul', 'Ezequias', 'Josias', 'B', 57, CURRENT_TIMESTAMP),
('Qual rainha visitou Salomão para ouvir sua sabedoria?', 'Rainha de Sabá', 'Rainha Ester', 'Rainha Jezabel', 'Rainha Vasti', 'Rainha Atalia', 'A', 58, CURRENT_TIMESTAMP),
('Após Salomão, o reino de Israel foi dividido em quantas partes principais?', 'Uma', 'Duas', 'Três', 'Quatro', 'Doze', 'B', 59, CURRENT_TIMESTAMP),
('Quem foi o profeta que enfrentou os profetas de Baal no monte Carmelo?', 'Eliseu', 'Elias', 'Isaías', 'Jeremias', 'Amós', 'B', 60, CURRENT_TIMESTAMP),
('Qual profeta recebeu porção dobrada do espírito de Elias?', 'Eliseu', 'Isaías', 'Miqueias', 'Oséias', 'Joel', 'A', 61, CURRENT_TIMESTAMP),
('Quem foi curado da lepra após mergulhar sete vezes no Jordão?', 'Naamã', 'Geazi', 'Uzias', 'Jó', 'Lázaro', 'A', 62, CURRENT_TIMESTAMP),
('Qual rei teve sua vida prolongada após orar a Deus?', 'Acabe', 'Ezequias', 'Manassés', 'Saul', 'Roboão', 'B', 63, CURRENT_TIMESTAMP),
('Qual rei encontrou o livro da Lei durante a reforma do templo?', 'Josias', 'Davi', 'Salomão', 'Acaz', 'Jeroboão', 'A', 64, CURRENT_TIMESTAMP),
('Quem foi levado ao céu em um redemoinho?', 'Moisés', 'Elias', 'Eliseu', 'Enoque', 'Isaías', 'B', 65, CURRENT_TIMESTAMP),
('Quem interpretou a escrita na parede para o rei Belsazar?', 'José', 'Daniel', 'Esdras', 'Neemias', 'Ezequiel', 'B', 66, CURRENT_TIMESTAMP),
('Quais três jovens foram lançados na fornalha ardente?', 'Sadraque, Mesaque e Abede-Nego', 'Pedro, Tiago e João', 'Davi, Jônatas e Saul', 'Moisés, Arão e Hur', 'Elias, Eliseu e Geazi', 'A', 67, CURRENT_TIMESTAMP),
('Qual império levou Judá ao exílio na Babilônia?', 'Egito', 'Assíria', 'Babilônia', 'Roma', 'Pérsia', 'C', 68, CURRENT_TIMESTAMP),
('Quem liderou a reconstrução dos muros de Jerusalém?', 'Esdras', 'Neemias', 'Zorobabel', 'Ageu', 'Malaquias', 'B', 69, CURRENT_TIMESTAMP),
('Quem foi escriba e ensinou a Lei ao povo após o exílio?', 'Neemias', 'Esdras', 'Daniel', 'Ezequiel', 'Zacarias', 'B', 70, CURRENT_TIMESTAMP),
('Qual profeta teve uma visão de ossos secos voltando à vida?', 'Isaías', 'Jeremias', 'Ezequiel', 'Daniel', 'Zacarias', 'C', 71, CURRENT_TIMESTAMP),
('Qual profeta escreveu sobre o Servo Sofredor?', 'Isaías', 'Jonas', 'Ageu', 'Naum', 'Obadias', 'A', 72, CURRENT_TIMESTAMP),
('Qual profeta tentou fugir para Társis?', 'Jonas', 'Amós', 'Oséias', 'Joel', 'Miquéias', 'A', 73, CURRENT_TIMESTAMP),
('Para qual cidade Jonas foi enviado para pregar?', 'Nínive', 'Babilônia', 'Jerusalém', 'Damasco', 'Tiro', 'A', 74, CURRENT_TIMESTAMP),
('Quem foi a mãe de Jesus?', 'Maria', 'Marta', 'Isabel', 'Ana', 'Salomé', 'A', 75, CURRENT_TIMESTAMP),
('Quem foi o pai de João Batista?', 'Zacarias', 'José', 'Simeão', 'Nicodemos', 'Jairo', 'A', 76, CURRENT_TIMESTAMP),
('Quem era a mãe de João Batista?', 'Maria', 'Isabel', 'Ana', 'Marta', 'Joana', 'B', 77, CURRENT_TIMESTAMP),
('Qual anjo anunciou a Maria o nascimento de Jesus?', 'Miguel', 'Gabriel', 'Rafael', 'Uriel', 'Querubim', 'B', 78, CURRENT_TIMESTAMP),
('Onde Jesus cresceu?', 'Belém', 'Jerusalém', 'Nazaré', 'Canaã', 'Jericó', 'C', 79, CURRENT_TIMESTAMP),
('Quem reconheceu Jesus como o Cordeiro de Deus?', 'João Batista', 'Pedro', 'Nicodemos', 'Pilatos', 'Herodes', 'A', 80, CURRENT_TIMESTAMP),
('Qual discípulo era cobrador de impostos antes de seguir Jesus?', 'Mateus', 'João', 'André', 'Filipe', 'Tomé', 'A', 81, CURRENT_TIMESTAMP),
('Qual discípulo ficou conhecido por duvidar da ressurreição de Jesus?', 'Pedro', 'Tomé', 'Tiago', 'Bartolomeu', 'André', 'B', 82, CURRENT_TIMESTAMP),
('Quem subiu numa árvore para ver Jesus passar?', 'Zaqueu', 'Nicodemos', 'Jairo', 'Bartimeu', 'Simão', 'A', 83, CURRENT_TIMESTAMP),
('Qual árvore Zaqueu subiu?', 'Oliveira', 'Sicômoro', 'Figueira', 'Cedro', 'Palmeira', 'B', 84, CURRENT_TIMESTAMP),
('Quem foi ressuscitado por Jesus depois de quatro dias no túmulo?', 'Jairo', 'Lázaro', 'Êutico', 'Estevão', 'Bartimeu', 'B', 85, CURRENT_TIMESTAMP),
('Quais irmãs eram próximas de Jesus e irmãs de Lázaro?', 'Maria e Marta', 'Raquel e Lia', 'Ester e Rute', 'Ana e Isabel', 'Priscila e Febe', 'A', 86, CURRENT_TIMESTAMP),
('Qual milagre envolveu cinco pães e dois peixes?', 'A pesca maravilhosa', 'A multiplicação dos alimentos', 'A cura do paralítico', 'A transformação da água', 'A tempestade acalmada', 'B', 87, CURRENT_TIMESTAMP),
('Quem caminhou sobre as águas ao encontro de Jesus?', 'João', 'Pedro', 'Tiago', 'André', 'Filipe', 'B', 88, CURRENT_TIMESTAMP),
('Qual discípulo traiu Jesus?', 'Pedro', 'Judas Iscariotes', 'Tomé', 'Mateus', 'Simão Zelote', 'B', 89, CURRENT_TIMESTAMP),
('Por quantas moedas Judas traiu Jesus?', '10 moedas de prata', '20 moedas de prata', '30 moedas de prata', '40 moedas de prata', '50 moedas de prata', 'C', 90, CURRENT_TIMESTAMP),
('Quem julgou Jesus e autorizou sua crucificação?', 'Herodes', 'Pilatos', 'Caifás', 'Anás', 'César Augusto', 'B', 91, CURRENT_TIMESTAMP),
('Quem ajudou Jesus a carregar a cruz?', 'Simão de Cirene', 'José de Arimateia', 'Nicodemos', 'João Marcos', 'Bartimeu', 'A', 92, CURRENT_TIMESTAMP),
('Quem pediu o corpo de Jesus para sepultá-lo?', 'Pedro', 'José de Arimateia', 'Tomé', 'André', 'Paulo', 'B', 93, CURRENT_TIMESTAMP),
('Quem foi a primeira pessoa a ver Jesus ressuscitado, segundo o relato de João?', 'Maria Madalena', 'Marta', 'Pedro', 'João', 'Isabel', 'A', 94, CURRENT_TIMESTAMP),
('Em qual monte Jesus ascendeu ao céu, segundo Atos?', 'Monte das Oliveiras', 'Monte Sinai', 'Monte Carmelo', 'Monte Moriá', 'Monte Hermom', 'A', 95, CURRENT_TIMESTAMP),
('Em qual dia o Espírito Santo foi derramado sobre os discípulos?', 'Páscoa', 'Pentecostes', 'Sábado', 'Dia da Expiação', 'Festa dos Tabernáculos', 'B', 96, CURRENT_TIMESTAMP),
('Quem pregou no Pentecostes e muitos se converteram?', 'Pedro', 'João', 'Paulo', 'Estevão', 'Barnabé', 'A', 97, CURRENT_TIMESTAMP),
('Quem foi o primeiro mártir cristão mencionado em Atos?', 'Tiago', 'Estevão', 'Pedro', 'Paulo', 'Filipe', 'B', 98, CURRENT_TIMESTAMP),
('Qual era o nome de Paulo antes de sua conversão?', 'Saulo', 'Simão', 'Silas', 'Sérgio', 'Sóstenes', 'A', 99, CURRENT_TIMESTAMP),
('Em qual caminho Paulo teve um encontro com Jesus ressuscitado?', 'Caminho de Jerusalém', 'Caminho de Damasco', 'Caminho de Emaús', 'Caminho de Jericó', 'Caminho de Samaria', 'B', 100, CURRENT_TIMESTAMP);
